<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net8.0</TargetFrameworks>
    <Authors>CM Talk</Authors>
    <Company>CM.com</Company>
    <Product>CM Talk SDK</Product>
    <Description>A software development kit to provide ways to interact with CM.com's Talk/Voice API.</Description>
    <PackageTags>voice, talk</PackageTags>
    <RepositoryUrl>https://github.com/cmdotcom/talk-sdk-dotnet</RepositoryUrl>
    <RepositoryType>Github</RepositoryType>
    <Copyright>$([System.DateTime]::UtcNow.Year) CM.com</Copyright>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageIcon>icon.png</PackageIcon>
    <Version>1.7.2</Version>
    <PackageProjectUrl>https://github.com/cmdotcom/talk-sdk-dotnet</PackageProjectUrl>
    <NeutralLanguage>en</NeutralLanguage>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <AssemblyVersion>1.7.2</AssemblyVersion>
    <FileVersion>1.7.2</FileVersion>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.2" />
    <None Include="$(MSBuildProjectDirectory)/../icon.png" Pack="true" Visible="false" PackagePath="" />
    <None Include="$(MSBuildProjectDirectory)/../LICENSE" Pack="true" PackagePath="" />
  </ItemGroup>

</Project>
